/* Portfolio content data — ported from the design system bundle
   (originally extracted from github.com/Dchirez/dchirez.github.io). */
export const PORTFOLIO = {
  identity: {
    name: 'Damien Chirez',
    handle: 'Damien.Dev',
    roleFr: 'Étudiant en BUT Informatique',
    roleEn: 'Computer Science Student',
    pitchFr: "Je conçois et développe des applications — du jeu console en C au fullstack Angular / Python. À la recherche d'une alternance en développement dès septembre 2026.",
    pitchEn: 'I design and build applications — from C console games to Angular / Python fullstack. Open to a development work-study (alternance) from September 2026.',
    statusFr: 'Open to work · Alternance dès septembre 2026',
    statusEn: 'Open to work · Alternance from September 2026',
    email: 'dchirez59@gmail.com',
    github: 'https://github.com/Dchirez?tab=repositories',
    linkedin: 'https://www.linkedin.com/in/damien-chirez-b0aa66355/',
    location: 'IUT de Lens, France',
    cv: '/cv/',
    formspree: 'https://formspree.io/f/mykbjbdb',
  },
  // devicon stack for the skills globe
  stack: [
    { tech: 'java', label: 'Java' }, { tech: 'c', label: 'C' },
    { tech: 'typescript', label: 'TypeScript' }, { tech: 'angular', label: 'Angular' },
    { tech: 'python', label: 'Python' }, { tech: 'kotlin', label: 'Kotlin' },
    { tech: 'html5', label: 'HTML5' }, { tech: 'css3', label: 'CSS3' },
    { tech: 'javascript', label: 'JavaScript' }, { tech: 'tailwindcss', label: 'Tailwind' },
    { tech: 'flask', label: 'Flask' }, { tech: 'git', label: 'Git' },
    { tech: 'gradle', label: 'Gradle' }, { tech: 'react', label: 'React' },
  ],
  formations: [
    { titreFr: '2ᵉ année — BUT Informatique', titreEn: '2nd year — IT Bachelor', org: 'IUT de Lens', years: '2025 – 2026', current: true },
    { titreFr: 'Baccalauréat Général', titreEn: 'High School Diploma', org: 'Lycée Jean Bart, Dunkerque', years: '2024 – 2025', current: false },
  ],
  projects: [
    { id: 'gmbmanager', logo: 'GMBLogo.png', titre: 'GMB Manager', techDisplay: 'Angular / Python / TypeScript', techs: ['angular', 'python', 'typescript'], type: 'perso', flagship: true, github: 'https://github.com/Dchirez/GMB_Manager.git',
      descFr: "Application de gestion des fiches Google My Business.", descEn: 'Google My Business profile management application.',
      detailsFr: "Application fullstack conçue pour aider les commerces locaux à gérer leur présence en ligne via Google My Business. Frontend Angular 21 + TypeScript + Tailwind, backend Python Flask. Intégration Google OAuth 2.0 et Business Profile API : scoring de complétude (0-100), gestion des avis, création de publications.",
      detailsEn: 'Fullstack app helping local businesses manage their Google My Business presence. Angular 21 + TypeScript + Tailwind frontend, Python Flask backend. Google OAuth 2.0 + Business Profile API: completeness scoring (0-100), review management, post creation.' },
    { id: 'puzzlecam', icon: '🧩', titre: 'Puzzle Cam', techDisplay: 'JavaScript / MediaPipe', techs: ['web'], type: 'perso', github: 'https://github.com/Dchirez/puzzle-cam', demo: 'https://dchirez.fr/puzzle-cam/',
      descFr: "Casse-tête 3×3 contrôlé aux gestes de la main.", descEn: '3×3 puzzle controlled by hand gestures.',
      detailsFr: "Casse-tête coulissant 3×3 jouable sans souris ni clavier : le contrôle se fait uniquement aux gestes de la main via la webcam (MediaPipe Hands). Pince des doigts pour cadrer, capturer et déplacer les pièces, poing fermé pour sauvegarder. Traitement de la vision en temps réel directement dans le navigateur.",
      detailsEn: 'A 3×3 sliding puzzle playable without mouse or keyboard: controlled entirely by hand gestures through the webcam (MediaPipe Hands). Pinch to frame, capture and move pieces, closed fist to save. Real-time computer vision running directly in the browser.' },
    { id: 'meteo', icon: '⛅', titre: 'Météo', techDisplay: 'React / Vite (PWA)', techs: ['react', 'web'], type: 'perso', github: 'https://github.com/Dchirez/meteo-app', demo: 'https://dchirez.fr/meteo-app/',
      descFr: "Application météo mobile-first installable (PWA).", descEn: 'Mobile-first installable weather app (PWA).',
      detailsFr: "Application météo React + Vite consommant l'API gratuite Open-Meteo (sans clé). Recherche de ville avec autocomplétion, géolocalisation, météo actuelle, prévisions horaires (24 h) et sur 7 jours, villes favorites (localStorage), bascule °C/°F. Pensée mobile-first et installable en PWA (manifest + service worker, fonctionnement hors-ligne).",
      detailsEn: 'Weather app built with React + Vite, consuming the free Open-Meteo API (no key). City search with autocomplete, geolocation, current weather, hourly (24 h) and 7-day forecasts, favourite cities (localStorage), °C/°F toggle. Mobile-first and installable as a PWA (manifest + service worker, basic offline support).' },
    { id: 'jeudelavie', icon: '🧬', titre: 'Jeu de la Vie', techDisplay: 'JavaScript / Canvas', techs: ['web'], type: 'perso', github: 'https://github.com/Dchirez/jeu-de-la-vie', demo: 'https://dchirez.fr/jeu-de-la-vie/',
      descFr: "Automate cellulaire de Conway, dessinable et interactif.", descEn: "Conway's Game of Life, drawable and interactive.",
      detailsFr: "Implémentation du Jeu de la Vie de John Horton Conway en JavaScript/Canvas pur. Grille torique dessinable à la souris/au doigt, motifs classiques (planeur, vaisseau léger, pulsar, canon à planeurs), lecture/pause, pas à pas, vitesse réglable et coloration des cellules selon leur âge.",
      detailsEn: "Implementation of Conway's Game of Life in vanilla JavaScript/Canvas. Toroidal grid drawable with mouse/touch, classic patterns (glider, lightweight spaceship, pulsar, glider gun), play/pause, step-by-step, adjustable speed and cell colouring by age." },
    { id: 'cryptobot', icon: '🤖', titre: 'Crypto Trading Bot', techDisplay: 'Python', techs: ['python'], type: 'perso', github: 'https://github.com/Dchirez/Crypto-Trading-Bot',
      descFr: "Bot de trading crypto automatisé sur Binance.", descEn: 'Automated crypto trading bot on Binance.',
      detailsFr: "Bot de trading automatisé sur Binance (spot) en Python. Stratégie basée sur la moyenne mobile (SMA) avec achat sur creux et revente sur objectif, gestion de plusieurs positions en parallèle avec stop-loss et take-profit. Modes simulation / testnet / réel, notifications et commandes interactives via Telegram (ccxt + python-dotenv).",
      detailsEn: 'Automated trading bot on Binance (spot) in Python. Simple moving average (SMA) strategy: buy on dips, sell on target, with multi-position management, stop-loss and take-profit. Simulation / testnet / live modes, plus Telegram notifications and interactive commands (ccxt + python-dotenv).' },
    { id: 'ordo', logo: 'OrdoReadLogo.png', titre: 'OrdoRead', techDisplay: 'Kotlin', techs: ['kotlin'], type: 'perso', github: 'https://github.com/Dchirez/OrdoRead',
      descFr: "Extraction et automatisation de rappels médicaux.", descEn: 'Extraction and automation of medical reminders.',
      detailsFr: "Application Kotlin pour le suivi médical : scanne une ordonnance avec l'appareil photo, extrait la prescription et ajoute automatiquement la posologie et les rappels dans le calendrier du smartphone.",
      detailsEn: 'Kotlin app for medical tracking: scans a prescription with the camera, extracts the data and automatically adds dosage and reminders to the smartphone calendar.' },
    { id: 'pacman', logo: 'PacManLogo.png', titre: 'Pac-Man', techDisplay: 'Java / Gradle', techs: ['java'], type: 'univ',
      descFr: "Reproduction du jeu culte avec patrons de conception.", descEn: 'Reproduction of the cult game with design patterns.',
      detailsFr: "Projet d'équipe (4) recréant Pac-Man de A à Z en Java / JavaFX avec Gradle. Implémentation rigoureuse de Design Patterns, méthode Agile, sprints réguliers et gestion de version stricte via Git.",
      detailsEn: 'Team project (4) recreating Pac-Man from scratch in Java / JavaFX with Gradle. Rigorous Design Pattern implementation, Agile method, regular sprints and strict Git version control.' },
    { id: 'coffre', icon: '🔐', titre: 'SecurWord', techDisplay: 'Java / TypeScript', techs: ['java', 'typescript'], type: 'perso',
      descFr: "Gestionnaire sécurisé de mots de passe.", descEn: 'Secure password manager.',
      detailsFr: "Coffre-fort numérique en Java / TypeScript : stockage chiffré des identifiants et fonctionnalité AutoFill qui pré-remplit les formulaires de connexion des sites enregistrés.",
      detailsEn: 'Digital vault in Java / TypeScript: encrypted credential storage and an AutoFill feature that pre-fills login forms on saved sites.' },
    { id: 'lensymphony', icon: '🎵', titre: 'LenSymphony', techDisplay: 'Java / XML', techs: ['java'], type: 'univ',
      descFr: "Synthétiseur musical lisant des partitions XML.", descEn: 'Musical synthesizer reading XML sheet music.',
      detailsFr: "Projet d'équipe (4) en méthode agile : un synthétiseur capable de lire et interpréter des partitions au format XML, développé en Java avec automatisation Gradle.",
      detailsEn: 'Team project (4), agile method: a synthesizer able to read and interpret XML sheet music, built in Java with Gradle automation.' },
    { id: 'mariage', icon: '💍', titre: 'UnOuiPourLaVie', techDisplay: 'HTML / CSS', techs: ['web'], type: 'univ', github: 'https://github.com/Dchirez/Site-web-UnOuiPourLaVie', demo: 'https://dchirez.fr/Site-web-UnOuiPourLaVie/',
      descFr: "Site vitrine complet pour organiser un mariage.", descEn: 'Complete showcase site for wedding planning.',
      detailsFr: "Site vitrine en HTML / CSS pur, conçu après analyse des sites de Wedding Planners de référence. Consolidation des bases en intégration web, design responsive et structuration sémantique.",
      detailsEn: 'Showcase site in pure HTML / CSS, designed after analysing reference Wedding Planner sites. Consolidated foundations in web integration, responsive design and semantic structure.' },
    { id: 'demineur', logo: 'DemineurLogo.png', titre: 'Démineur', techDisplay: 'C', techs: ['c'], type: 'perso', github: 'https://github.com/Dchirez/Demineur-C',
      descFr: "Génération de grille et algorithme de déminage.", descEn: 'Grid generation and minesweeper algorithm.',
      detailsFr: "Reproduction du Démineur en console (C) : génération dynamique d'une grille, répartition aléatoire des mines selon la difficulté, révélation de cases et pose de drapeaux par coordonnées.",
      detailsEn: 'Minesweeper reproduction in the console (C): dynamic grid generation, random mine distribution by difficulty, reveal cells and place flags by coordinates.' },
    { id: 'bataille', logo: 'BatailleLogo.png', titre: 'Bataille Navale', techDisplay: 'C', techs: ['c'], type: 'perso', github: 'https://github.com/Dchirez/Bataille-Navale-C',
      descFr: "Jeu de plateau interactif contre une IA basique.", descEn: 'Interactive board game against a basic AI.',
      detailsFr: "Bataille navale jouable au terminal, en C. Manipulation de matrices pour la grille de jeu et IA basique permettant d'affronter l'ordinateur.",
      detailsEn: 'Battleship playable in the terminal, in C. Matrix manipulation for the game grid and a basic AI to play against the computer.' },
    { id: 'quizz', logo: 'QuizzLogo.png', titre: 'Quizz Culture G', techDisplay: 'C', techs: ['c'], type: 'perso', github: 'https://github.com/Dchirez/Quizz-Culture-G-C',
      descFr: "Jeu de questions-réponses interactif en console.", descEn: 'Interactive console trivia game.',
      detailsFr: "Un de mes premiers projets en C : un quizz de culture générale en console. Maîtrise des bases — programmation impérative, entrées/sorties standard, structures de contrôle.",
      detailsEn: 'One of my first C projects: a general-knowledge console quiz. Mastery of the basics — imperative programming, standard I/O, control structures.' },
    { id: 'justeprix', logo: 'JustePrixLogo.png', titre: 'Juste Prix', techDisplay: 'C', techs: ['c'], type: 'perso', github: 'https://github.com/Dchirez/Juste-Prix-C',
      descFr: "Mini-jeu basé sur le célèbre concept télévisé.", descEn: 'Mini-game based on the famous TV concept.',
      detailsFr: "Mini-jeu en C reprenant le Juste Prix : prix aléatoire à deviner avec niveaux de difficulté paramétrables. Introduction à la logique algorithmique et à l'aléatoire.",
      detailsEn: 'C mini-game based on The Price is Right: random price to guess with adjustable difficulty. An introduction to algorithmic logic and randomness.' },
    { id: 'marathon', icon: '💻', titre: 'Marathon Web', techDisplay: 'Web', techs: ['web'], type: 'univ',
      descFr: "Hackathon interdisciplinaire en développement web.", descEn: 'Interdisciplinary web development hackathon.',
      detailsFr: "Événement intensif avec les étudiants MMI : concevoir, maquetter et développer un site de blog fonctionnel en temps très limité. Travail d'équipe sous pression.",
      detailsEn: 'Intensive event with MMI students: design, mock up and build a functional blog site in a very short time. Teamwork under pressure.' },
  ],
};

export const LOGO = (f) => `/logo/${f}`;
